### ISSUE TITLE
npm test throws an error: Error: Cannot find module '../lib/disposable'

### ISSUE THREAD

**Issue by ThomasHalwax** [syncpoint/ODIN#12]
Running ```npm test``` throws an error:

```javascript
else throw err
           ^

Error: Cannot find module '../lib/disposable'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/Thomas/Dev/ODIN/test/disposable-test.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /Users/Thomas/Dev/ODIN/node_modules/mocha/lib/mocha.js:330:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/Thomas/Dev/ODIN/node_modules/mocha/lib/mocha.js:327:14)
    at Mocha.run (/Users/Thomas/Dev/ODIN/node_modules/mocha/lib/mocha.js:804:10)
    at Object.exports.singleRun (/Users/Thomas/Dev/ODIN/node_modules/mocha/lib/cli/run-helpers.js:207:16)
    at exports.runMocha (/Users/Thomas/Dev/ODIN/node_modules/mocha/lib/cli/run-helpers.js:300:13)
    at Object.exports.handler.argv [as handler] (/Users/Thomas/Dev/ODIN/node_modules/mocha/lib/cli/run.js:296:3)
    at Object.runCommand (/Users/Thomas/Dev/ODIN/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/Users/Thomas/Dev/ODIN/node_modules/yargs/yargs.js:1104:24)
    at Object.parse (/Users/Thomas/Dev/ODIN/node_modules/yargs/yargs.js:566:25)
    at Object.exports.main (/Users/Thomas/Dev/ODIN/node_modules/mocha/lib/cli/cli.js:63:6)
    at Object.<anonymous> (/Users/Thomas/Dev/ODIN/node_modules/mocha/bin/_mocha:10:23)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! Test failed.  See above for more details.
```

**Comment by dehmer** [comment]
fixed.
